name: perl-math-gsl-macos
on:
    push:
      branches:
      - '*'
    pull_request:
        branches:
        - '*'
    workflow_dispatch:
jobs:
  build-perl:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.40'
    - name: Build Math::GSL
      run: |
       cpanm Alien::GSL
       cpanm Module::Build
       perl Build.PL
       ./Build installdeps --cpan_client cpanm
       ./Build
    - name: Test Math::GSL
      run: |
       ./Build test

